"""empty message

Revision ID: 0eaabcc7cb32
Revises: fc837d2eb9f0
Create Date: 2021-11-08 18:47:36.747909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0eaabcc7cb32'
down_revision = 'fc837d2eb9f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('complains',
    sa.Column('complain_id', sa.Integer(), nullable=False),
    sa.Column('complain_author', sa.Integer(), nullable=True),
    sa.Column('complain_subject', sa.String(length=50), nullable=True),
    sa.Column('complain_body', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('complain_id')
    )
    op.create_table('login_log',
    sa.Column('login_log_id', sa.Integer(), nullable=False),
    sa.Column('login_date', sa.Integer(), nullable=True),
    sa.Column('login_time', sa.Integer(), nullable=True),
    sa.Column('login_user', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('login_log_id')
    )
    op.create_table('messages',
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('message_author', sa.Integer(), nullable=True),
    sa.Column('message_subject', sa.String(length=50), nullable=True),
    sa.Column('message_body', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('message_id')
    )
    op.create_table('projects',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('project_name', sa.String(length=25), nullable=True),
    sa.Column('project_members', sa.Integer(), nullable=True),
    sa.Column('project_description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('project_id'),
    sa.UniqueConstraint('project_name')
    )
    op.create_table('storage',
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('article_code', sa.String(length=20), nullable=True),
    sa.Column('article_name', sa.String(length=50), nullable=True),
    sa.Column('article_lot_number', sa.String(length=20), nullable=True),
    sa.Column('article_purchase_date', sa.Integer(), nullable=True),
    sa.Column('article_purchase_user', sa.Integer(), nullable=True),
    sa.Column('article_delivery_date', sa.Integer(), nullable=True),
    sa.Column('article_delivery_quantity', sa.Integer(), nullable=True),
    sa.Column('article_units', sa.String(length=10), nullable=True),
    sa.Column('article_initial_quantity', sa.Integer(), nullable=True),
    sa.Column('article_used', sa.Integer(), nullable=True),
    sa.Column('article_user', sa.Integer(), nullable=True),
    sa.Column('article_remaining_quantity', sa.Integer(), nullable=True),
    sa.Column('article_project', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('article_id'),
    sa.UniqueConstraint('article_code'),
    sa.UniqueConstraint('article_lot_number')
    )
    op.drop_table('obieg')
    op.drop_table('chemical')
    op.add_column('user', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('user', sa.Column('user_name', sa.String(length=25), nullable=True))
    op.add_column('user', sa.Column('user_email', sa.String(length=35), nullable=True))
    op.add_column('user', sa.Column('user_password', sa.String(length=25), nullable=True))
    op.add_column('user', sa.Column('user_project', sa.String(length=50), nullable=True))
    op.add_column('user', sa.Column('user_login_log', sa.String(length=50), nullable=True))
    op.add_column('user', sa.Column('user_complain', sa.String(length=250), nullable=True))
    op.create_unique_constraint(None, 'user', ['user_email'])
    op.drop_column('user', 'name')
    op.drop_column('user', 'logowanie')
    op.drop_column('user', 'password')
    op.drop_column('user', 'email')
    op.drop_column('user', 'id')
    op.drop_column('user', 'obieg')
    op.drop_column('user', 'complain')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('complain', sa.VARCHAR(length=250), nullable=True))
    op.add_column('user', sa.Column('obieg', sa.VARCHAR(length=50), nullable=True))
    op.add_column('user', sa.Column('id', sa.INTEGER(), nullable=False))
    op.add_column('user', sa.Column('email', sa.VARCHAR(length=25), nullable=True))
    op.add_column('user', sa.Column('password', sa.VARCHAR(length=25), nullable=True))
    op.add_column('user', sa.Column('logowanie', sa.VARCHAR(length=50), nullable=True))
    op.add_column('user', sa.Column('name', sa.VARCHAR(length=25), nullable=True))
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'user_complain')
    op.drop_column('user', 'user_login_log')
    op.drop_column('user', 'user_project')
    op.drop_column('user', 'user_password')
    op.drop_column('user', 'user_email')
    op.drop_column('user', 'user_name')
    op.drop_column('user', 'user_id')
    op.create_table('chemical',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('kod_towaru', sa.VARCHAR(length=10), nullable=True),
    sa.Column('nazwa', sa.VARCHAR(length=25), nullable=True),
    sa.Column('opakowanie', sa.VARCHAR(length=25), nullable=True),
    sa.Column('przychod', sa.INTEGER(), nullable=True),
    sa.Column('rozchod', sa.INTEGER(), nullable=True),
    sa.Column('stan_koncowy', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kod_towaru')
    )
    op.create_table('obieg',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nazwa', sa.VARCHAR(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nazwa')
    )
    op.drop_table('storage')
    op.drop_table('projects')
    op.drop_table('messages')
    op.drop_table('login_log')
    op.drop_table('complains')
    # ### end Alembic commands ###
