"""empty message

Revision ID: 1ea1cd055b52
Revises: 6d0fc609c90a
Create Date: 2021-12-07 21:45:30.762688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ea1cd055b52'
down_revision = '6d0fc609c90a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('complaints',
    sa.Column('complain_id', sa.Integer(), nullable=False),
    sa.Column('complain_subject', sa.String(length=50), nullable=True),
    sa.Column('complain_body', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('complain_id')
    )
    op.drop_table('complains')
    op.alter_column('login_log', 'login_date',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.drop_constraint(None, 'login_log', type_='foreignkey')
    op.drop_column('login_log', 'login_user_id')
    op.alter_column('messages', 'message_body',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('messages', 'message_author')
    op.drop_column('projects', 'project_members')
    op.alter_column('storage', 'article_purchase_date',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('storage', 'article_delivery_date',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('storage', 'article_project')
    op.drop_column('storage', 'article_purchase_user')
    op.drop_column('storage', 'article_user')
    op.alter_column('user', 'user_email',
               existing_type=sa.VARCHAR(length=25),
               nullable=False)
    op.create_unique_constraint(None, 'user', ['user_email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.alter_column('user', 'user_email',
               existing_type=sa.VARCHAR(length=25),
               nullable=True)
    op.add_column('storage', sa.Column('article_user', sa.INTEGER(), nullable=True))
    op.add_column('storage', sa.Column('article_purchase_user', sa.INTEGER(), nullable=True))
    op.add_column('storage', sa.Column('article_project', sa.INTEGER(), nullable=True))
    op.alter_column('storage', 'article_delivery_date',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('storage', 'article_purchase_date',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('projects', sa.Column('project_members', sa.INTEGER(), nullable=True))
    op.add_column('messages', sa.Column('message_author', sa.VARCHAR(length=35), nullable=True))
    op.alter_column('messages', 'message_body',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.add_column('login_log', sa.Column('login_user_id', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'login_log', 'user', ['login_user_id'], ['id'])
    op.alter_column('login_log', 'login_date',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.create_table('complains',
    sa.Column('complain_id', sa.INTEGER(), nullable=False),
    sa.Column('complain_author', sa.INTEGER(), nullable=True),
    sa.Column('complain_subject', sa.VARCHAR(length=50), nullable=True),
    sa.Column('complain_body', sa.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('complain_id')
    )
    op.drop_table('complaints')
    # ### end Alembic commands ###
