"""empty message

Revision ID: 5ada5ede5f3b
Revises: 0eaabcc7cb32
Create Date: 2021-11-08 18:49:30.248848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ada5ede5f3b'
down_revision = '0eaabcc7cb32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=25), nullable=True),
    sa.Column('user_email', sa.String(length=35), nullable=True),
    sa.Column('user_password', sa.String(length=25), nullable=True),
    sa.Column('user_project', sa.String(length=50), nullable=True),
    sa.Column('user_login_log', sa.String(length=50), nullable=True),
    sa.Column('user_complain', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('user_email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
