"""empty message

Revision ID: 73bfcee39a14
Revises: de8172293d46
Create Date: 2021-12-14 22:05:12.682039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73bfcee39a14'
down_revision = 'de8172293d46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'user', ['message_author'], ['id'])
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.create_foreign_key(None, 'projects', 'user', ['project_members'], ['id'])
    op.add_column('storage', sa.Column('article_user', sa.String(length=35), nullable=False))
    op.drop_constraint(None, 'storage', type_='foreignkey')
    op.create_foreign_key(None, 'storage', 'user', ['article_purchase_user'], ['id'])
    op.create_foreign_key(None, 'storage', 'user', ['article_user'], ['user_email'])
    op.create_foreign_key(None, 'user', 'projects', ['user_project'], ['project_id'])
    op.create_foreign_key(None, 'user', 'login', ['user_login_log'], ['login_log_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_constraint(None, 'storage', type_='foreignkey')
    op.drop_constraint(None, 'storage', type_='foreignkey')
    op.create_foreign_key(None, 'storage', 'user', ['article_purchase_user'], ['user_email'])
    op.drop_column('storage', 'article_user')
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.create_foreign_key(None, 'projects', 'user', ['project_members'], ['user_email'])
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'user', ['message_author'], ['user_email'])
    # ### end Alembic commands ###
