"""empty message

Revision ID: 805b5d450b65
Revises: aabf76412bf1
Create Date: 2021-11-03 21:25:06.045587

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '805b5d450b65'
down_revision = 'aabf76412bf1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('obieg', sa.String(length=50), nullable=True))
    op.add_column('user', sa.Column('logowanie', sa.String(length=50), nullable=True))
    op.add_column('user', sa.Column('complain', sa.String(length=250), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'complain')
    op.drop_column('user', 'logowanie')
    op.drop_column('user', 'obieg')
    # ### end Alembic commands ###
