"""empty message

Revision ID: 8134b62696fa
Revises: 805b5d450b65
Create Date: 2021-11-03 21:45:07.036262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8134b62696fa'
down_revision = '805b5d450b65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chemical',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kod_towaru', sa.String(length=10), nullable=True),
    sa.Column('nazwa', sa.String(length=25), nullable=True),
    sa.Column('opakowanie', sa.String(length=25), nullable=True),
    sa.Column('przychod', sa.Integer(), nullable=True),
    sa.Column('rozchod', sa.Integer(), nullable=True),
    sa.Column('stan_koncowy', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kod_towaru')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chemical')
    # ### end Alembic commands ###
