"""empty message

Revision ID: ac6e6738f0e8
Revises: 81386b9bc88f
Create Date: 2021-12-14 21:37:43.340472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac6e6738f0e8'
down_revision = '81386b9bc88f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'complaints', type_='foreignkey')
    op.create_foreign_key(None, 'complaints', 'user', ['complain_author'], ['id'])
    op.drop_constraint(None, 'login_log', type_='foreignkey')
    op.create_foreign_key(None, 'login_log', 'user', ['login_user_id'], ['id'])
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'user', ['message_author'], ['id'])
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.create_foreign_key(None, 'projects', 'user', ['project_members'], ['id'])
    op.drop_constraint(None, 'storage', type_='foreignkey')
    op.create_foreign_key(None, 'storage', 'user', ['article_purchase_user'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'storage', type_='foreignkey')
    op.create_foreign_key(None, 'storage', 'user', ['article_purchase_user'], ['user_email'])
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.create_foreign_key(None, 'projects', 'user', ['project_members'], ['user_email'])
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'user', ['message_author'], ['user_email'])
    op.drop_constraint(None, 'login_log', type_='foreignkey')
    op.create_foreign_key(None, 'login_log', 'user', ['login_user_id'], ['user_email'])
    op.drop_constraint(None, 'complaints', type_='foreignkey')
    op.create_foreign_key(None, 'complaints', 'user', ['complain_author'], ['user_email'])
    # ### end Alembic commands ###
