"""empty message

Revision ID: b1da99939ac2
Revises: 
Create Date: 2021-12-27 18:38:29.518709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1da99939ac2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('complaints',
    sa.Column('complaint_id', sa.Integer(), nullable=False),
    sa.Column('complaint_author', sa.String(length=35), nullable=False),
    sa.Column('complaint_subject', sa.String(length=50), nullable=True),
    sa.Column('complaint_body', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['complaint_author'], ['user.user_email'], ),
    sa.PrimaryKeyConstraint('complaint_id')
    )
    op.create_table('login',
    sa.Column('login_log_id', sa.Integer(), nullable=False),
    sa.Column('login_user_id', sa.String(length=35), nullable=False),
    sa.Column('login_date', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['login_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('login_log_id')
    )
    op.create_table('projects',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('project_name', sa.String(length=25), nullable=True),
    sa.Column('project_members', sa.String(length=35), nullable=False),
    sa.Column('project_description', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['project_members'], ['user.id'], ),
    sa.PrimaryKeyConstraint('project_id'),
    sa.UniqueConstraint('project_name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_first_name', sa.String(length=25), nullable=True),
    sa.Column('user_second_name', sa.String(length=35), nullable=True),
    sa.Column('user_company_initials', sa.String(length=4), nullable=True),
    sa.Column('user_password', sa.String(length=25), nullable=True),
    sa.Column('user_email', sa.String(length=35), nullable=False),
    sa.Column('user_project', sa.String(length=50), nullable=True),
    sa.Column('user_login_log', sa.String(length=50), nullable=True),
    sa.Column('user_complaint', sa.Text(), nullable=True),
    sa.Column('is_confirmed', sa.Boolean(), nullable=True),
    sa.Column('confirmation_code', sa.String(length=65), nullable=True),
    sa.ForeignKeyConstraint(['user_complaint'], ['complaints.complaint_id'], ),
    sa.ForeignKeyConstraint(['user_login_log'], ['login.login_log_id'], ),
    sa.ForeignKeyConstraint(['user_project'], ['projects.project_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_email')
    )
    op.create_table('messages',
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('message_author', sa.String(length=35), nullable=False),
    sa.Column('message_subject', sa.String(length=50), nullable=True),
    sa.Column('message_body', sa.Text(), nullable=False),
    sa.Column('message_date', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['message_author'], ['user.id'], ),
    sa.PrimaryKeyConstraint('message_id')
    )
    op.create_table('storage',
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('article_code', sa.String(length=20), nullable=True),
    sa.Column('article_name', sa.String(length=50), nullable=True),
    sa.Column('article_lot_number', sa.String(length=20), nullable=True),
    sa.Column('article_purchase_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('article_purchase_user', sa.String(length=35), nullable=False),
    sa.Column('article_delivery_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('article_delivery_quantity', sa.Integer(), nullable=True),
    sa.Column('article_units', sa.String(length=10), nullable=True),
    sa.Column('article_initial_quantity', sa.Integer(), nullable=True),
    sa.Column('article_used', sa.Integer(), nullable=True),
    sa.Column('article_user', sa.String(length=35), nullable=False),
    sa.Column('article_remaining_quantity', sa.Integer(), nullable=True),
    sa.Column('article_project', sa.String(length=35), nullable=False),
    sa.ForeignKeyConstraint(['article_project'], ['projects.project_id'], ),
    sa.ForeignKeyConstraint(['article_purchase_user'], ['user.id'], ),
    sa.ForeignKeyConstraint(['article_user'], ['user.user_email'], ),
    sa.PrimaryKeyConstraint('article_id'),
    sa.UniqueConstraint('article_code'),
    sa.UniqueConstraint('article_lot_number')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('storage')
    op.drop_table('messages')
    op.drop_table('user')
    op.drop_table('projects')
    op.drop_table('login')
    op.drop_table('complaints')
    # ### end Alembic commands ###
