"""empty message

Revision ID: de8172293d46
Revises: ac6e6738f0e8
Create Date: 2021-12-14 21:56:04.943416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de8172293d46'
down_revision = 'ac6e6738f0e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login',
    sa.Column('login_log_id', sa.Integer(), nullable=False),
    sa.Column('login_user_id', sa.String(length=35), nullable=False),
    sa.Column('login_date', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['login_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('login_log_id')
    )
    op.drop_table('login_log')
    op.drop_constraint(None, 'complaints', type_='foreignkey')
    op.create_foreign_key(None, 'complaints', 'user', ['complain_author'], ['id'])
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'user', ['message_author'], ['id'])
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.create_foreign_key(None, 'projects', 'user', ['project_members'], ['id'])
    op.add_column('storage', sa.Column('article_user', sa.String(length=35), nullable=False))
    op.drop_constraint(None, 'storage', type_='foreignkey')
    op.create_foreign_key(None, 'storage', 'user', ['article_purchase_user'], ['id'])
    op.create_foreign_key(None, 'storage', 'user', ['article_user'], ['user_email'])
    op.create_foreign_key(None, 'user', 'projects', ['user_project'], ['project_id'])
    op.create_foreign_key(None, 'user', 'login', ['user_login_log'], ['login_log_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_constraint(None, 'storage', type_='foreignkey')
    op.drop_constraint(None, 'storage', type_='foreignkey')
    op.create_foreign_key(None, 'storage', 'user', ['article_purchase_user'], ['user_email'])
    op.drop_column('storage', 'article_user')
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.create_foreign_key(None, 'projects', 'user', ['project_members'], ['user_email'])
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'user', ['message_author'], ['user_email'])
    op.drop_constraint(None, 'complaints', type_='foreignkey')
    op.create_foreign_key(None, 'complaints', 'user', ['complain_author'], ['user_email'])
    op.create_table('login_log',
    sa.Column('login_log_id', sa.INTEGER(), nullable=False),
    sa.Column('login_user_id', sa.VARCHAR(length=35), nullable=False),
    sa.Column('login_date', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['login_user_id'], ['user.user_email'], ),
    sa.PrimaryKeyConstraint('login_log_id')
    )
    op.drop_table('login')
    # ### end Alembic commands ###
