"""empty message

Revision ID: e3a727f538d3
Revises: e47f502b95be
Create Date: 2021-11-23 20:50:11.861686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3a727f538d3'
down_revision = 'e47f502b95be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_confirmed', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('confirmation_code', sa.String(length=65), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'confirmation_code')
    op.drop_column('user', 'is_confirmed')
    # ### end Alembic commands ###
