"""empty message

Revision ID: e47f502b95be
Revises: 
Create Date: 2021-11-09 21:10:00.030039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e47f502b95be'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('complains',
    sa.Column('complain_id', sa.Integer(), nullable=False),
    sa.Column('complain_author', sa.Integer(), nullable=True),
    sa.Column('complain_subject', sa.String(length=50), nullable=True),
    sa.Column('complain_body', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('complain_id')
    )
    op.create_table('messages',
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('message_author', sa.String(length=35), nullable=True),
    sa.Column('message_subject', sa.String(length=50), nullable=True),
    sa.Column('message_body', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('message_id')
    )
    op.create_table('projects',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('project_name', sa.String(length=25), nullable=True),
    sa.Column('project_members', sa.Integer(), nullable=True),
    sa.Column('project_description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('project_id'),
    sa.UniqueConstraint('project_name')
    )
    op.create_table('storage',
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('article_code', sa.String(length=20), nullable=True),
    sa.Column('article_name', sa.String(length=50), nullable=True),
    sa.Column('article_lot_number', sa.String(length=20), nullable=True),
    sa.Column('article_purchase_date', sa.Integer(), nullable=True),
    sa.Column('article_purchase_user', sa.Integer(), nullable=True),
    sa.Column('article_delivery_date', sa.Integer(), nullable=True),
    sa.Column('article_delivery_quantity', sa.Integer(), nullable=True),
    sa.Column('article_units', sa.String(length=10), nullable=True),
    sa.Column('article_initial_quantity', sa.Integer(), nullable=True),
    sa.Column('article_used', sa.Integer(), nullable=True),
    sa.Column('article_user', sa.Integer(), nullable=True),
    sa.Column('article_remaining_quantity', sa.Integer(), nullable=True),
    sa.Column('article_project', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('article_id'),
    sa.UniqueConstraint('article_code'),
    sa.UniqueConstraint('article_lot_number')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_first_name', sa.String(length=25), nullable=True),
    sa.Column('user_second_name', sa.String(length=35), nullable=True),
    sa.Column('user_company_initials', sa.String(length=4), nullable=True),
    sa.Column('user_password', sa.String(length=25), nullable=True),
    sa.Column('user_email', sa.String(length=25), nullable=True),
    sa.Column('user_project', sa.String(length=50), nullable=True),
    sa.Column('user_login_log', sa.String(length=50), nullable=True),
    sa.Column('user_complain', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_second_name')
    )
    op.create_table('login_log',
    sa.Column('login_log_id', sa.Integer(), nullable=False),
    sa.Column('login_user_id', sa.Integer(), nullable=True),
    sa.Column('login_date', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['login_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('login_log_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('login_log')
    op.drop_table('user')
    op.drop_table('storage')
    op.drop_table('projects')
    op.drop_table('messages')
    op.drop_table('complains')
    # ### end Alembic commands ###
