"""empty message

Revision ID: f8206cae8b1f
Revises: 1ea1cd055b52
Create Date: 2021-12-07 21:50:38.843117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8206cae8b1f'
down_revision = '1ea1cd055b52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('complaints', sa.Column('complain_author', sa.String(length=35), nullable=False))
    op.create_foreign_key(None, 'complaints', 'user', ['complain_author'], ['user_email'])
    op.alter_column('login_log', 'login_user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('login_log', 'login_date',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.drop_constraint(None, 'login_log', type_='foreignkey')
    op.create_foreign_key(None, 'login_log', 'user', ['login_user_id'], ['user_email'])
    op.alter_column('messages', 'message_author',
               existing_type=sa.VARCHAR(length=35),
               nullable=False)
    op.alter_column('messages', 'message_body',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.create_foreign_key(None, 'messages', 'user', ['message_author'], ['user_email'])
    op.alter_column('projects', 'project_members',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_foreign_key(None, 'projects', 'user', ['project_members'], ['user_email'])
    op.alter_column('storage', 'article_purchase_date',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('storage', 'article_purchase_user',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('storage', 'article_delivery_date',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('storage', 'article_user',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('storage', 'article_project',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_foreign_key(None, 'storage', 'user', ['article_purchase_user'], ['user_email'])
    op.create_foreign_key(None, 'storage', 'projects', ['article_project'], ['project_id'])
    op.create_foreign_key(None, 'storage', 'user', ['article_user'], ['user_email'])
    op.alter_column('user', 'user_email',
               existing_type=sa.VARCHAR(length=25),
               nullable=False)
    op.create_unique_constraint(None, 'user', ['user_email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.alter_column('user', 'user_email',
               existing_type=sa.VARCHAR(length=25),
               nullable=True)
    op.drop_constraint(None, 'storage', type_='foreignkey')
    op.drop_constraint(None, 'storage', type_='foreignkey')
    op.drop_constraint(None, 'storage', type_='foreignkey')
    op.alter_column('storage', 'article_project',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('storage', 'article_user',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('storage', 'article_delivery_date',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('storage', 'article_purchase_user',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('storage', 'article_purchase_date',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.alter_column('projects', 'project_members',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.alter_column('messages', 'message_body',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('messages', 'message_author',
               existing_type=sa.VARCHAR(length=35),
               nullable=True)
    op.drop_constraint(None, 'login_log', type_='foreignkey')
    op.create_foreign_key(None, 'login_log', 'user', ['login_user_id'], ['id'])
    op.alter_column('login_log', 'login_date',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('login_log', 'login_user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'complaints', type_='foreignkey')
    op.drop_column('complaints', 'complain_author')
    # ### end Alembic commands ###
