"""empty message

Revision ID: fc837d2eb9f0
Revises: 2cd230c2ec4a
Create Date: 2021-11-03 22:12:40.374556

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc837d2eb9f0'
down_revision = '2cd230c2ec4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'user', 'obieg', ['obieg'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    # ### end Alembic commands ###
